blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/SashaBusinaro/yaml-compose-sorter/discussions
    about: Ask questions, share ideas, and connect with other users.
